### ISSUE TITLE
せっかく消した内容また元に戻ってて草

### ISSUE THREAD

**Issue by C6H2Cl2** [VioletTeam/VioletCraft#15]

**Comment by C6H2Cl2** [comment]
git reset (コミットのハッシュ)
git push -f
でgitから抹消できますよ

**Comment by keikun4649** [comment]
自分が確認した際はすでにこれですが

**Comment by C6H2Cl2** [comment]
masterは完全にロールバックしたからおそらくbaguのブランチにmergeしたのが残っていたと思われ

**Comment by keikun4649** [comment]
まぁいいですよ
こっちはこっちで確認したいことが多々あるので今の状態で復元するので
今は別に元に戻すとかそういう話じゃないので、もう触れなくていいですよ
mergeした部分の消し方も　コミットの消し方も　以前の状態に戻す方法もやり方は知ってます

それにマージしてた部分が残ってるとか言ってますけど、私もbaguさんもあれからマージもしてないので戻るはずがないんです
なのでパラジさんの状態ですでにあの状態です。

**Comment by C6H2Cl2** [comment]
あ、残ってた原因わかったわ
やっぱりresetじゃなくてrevertしたほうが良かったなこりゃ
まぁせいぜい頑張ってくださいな
